[SVR-298] 던전점령권 판매 기능 추가
not-blond-beard/savor22b pull request #160
Opened 2024-04-14 14:28 UTC by Atralupus

# TL;DR

SSIA
# 배경 및 목표

# 작업 사항

# 리뷰어가 중점적으로 볼 사항

2024-04-14 14:35 UTC, upa-r-upa requested changes
작업이 전체적으로 현재 State랑 안맞게 작업된 것 같아요
점령권을 시스템에 판매 한거니까 현재 점령중인 사람을 기록하는 GlobalDungeonState에서 지워야 하는건데
엉뚱한 history가 삭제되고 있네요

2024-04-16 14:59 UTC, upa-r-upa commented
@Atralupus 잊고 계신 것 같아 리마인드 해드립니다..

2024-04-16 17:28 UTC, Atralupus commented
> 작업이 전체적으로 현재 State랑 안맞게 작업된 것 같아요 점령권을 시스템에 판매 한거니까 현재 점령중인 사람을 기록하는 GlobalDungeonState에서 지워야 하는건데 엉뚱한 history가 삭제되고 있네요

수정해봤습니다

2024-04-16 17:29 UTC, upa-r-upa approved these changes
너무 고생하셨습니다~

2024-04-16 17:32 UTC, merged