[무역 상점] 인벤토리 및 판매목록 구현
not-blond-beard/savor22b pull request #190
Opened 2024-05-22 16:37 UTC by kth1888

# TL;DR

무역 상점 화면에 내 아이템과 상대방과 내가 올린 물품을 볼 수 있습니다.
현재는 내 아이템만 볼 수 있는 상황이고
예시를 위한 내가 올린 물품을 만드는 쿼리 테스트 코드를 작성중입니다.

2024-05-26 07:35 UTC, Atralupus requested changes

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/gql/query_executor.gd
> +			print(data) # 지워야함
네 지워주시죠

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +const SellListScn = preload("res://scenes/market/sell_list.tscn")
변수명이랑 신 이름이 좀 이상한데 백엔드랑 용어 통일 할까요

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +
띄어쓰기를 전체적으로 다 한칸씩만 하도록 해놨습니다. 파일 전체적으로 통일해주세요

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +	print(inventory_state)
디버깅용 프린트들은 불필요합니다. 작업이 끝났다면 제거해주시고 작업 중에도 디버거로 찍어서 보시는게 좋습니다

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +func test_register():
테스트 코드들은 삭제해주세요

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +func query_action(query_executor): # query with no args
메소드 명을 더 명확하게 해주세요 query_action은 어떤걸 의미하는지 잘 모르겠습니다

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +func _on_test_button_down():
테스트 22

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/my_item.gd
> +#@onready var food_name = $M/V/Name
필요없는 코드들은 주석말고 아예 제거해주세요

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/my_item.gd
> +	print(info)
print만 찍는다면 테스트 코드인건가요?

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/posted_item.gd
> +	if description_label == null:
계속 신이 반복해서 사용되는 것 같은데 이런 용도라면 하나로 만들어서 재활용해주세요

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/posted_item.gd
> +	if description_label == null:
label의 값을 인자로 받으시면 될 듯 합니다

2024-05-26 07:35 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/posted_item.gd
> +extends Control
해당 신도 이름 변경 부탁드립니다

2024-05-26 07:35 UTC, Atralupus commented
그리고 리베이스 필요합니다

2024-05-26 09:35 UTC, kth1888 commented on frontend/Savor-22b/scenes/market/posted_item.gd
> +	if description_label == null:
my_item과 posted_item은 다른 씬으로 구성해서 괜찮을 것 같습니다.

2024-05-26 11:53 UTC, Atralupus commented
그리고 무역은 마을에서 활동을 했어야 사용할 수 있으니 부엌, 농장쪽에 진입 버튼을 두는게 맞아보입니다

2024-05-26 12:17 UTC, upa-r-upa commented
지나가는 길에 봤는데요. 일단 작업 고생하셨습니다.
코드는 오프 기간이라 안읽었고 그냥 사진과 PR에 올려진 기능 내용으로만 간단하게 리뷰 답니다.  
문제점이 좀 있는데요, 지원님이 말씀해주신 건 제외하고 간단하게 적어봅니다..

1. 일단 적어도 직업 안틀어보고 이 PR안에서 이 기능을 리뷰해드리려면 화면별 사진 정도는 전부 올라와야 한다고 생각하는데
당장 짧게만 봐도 내가 올린 판매 목록 탭은 PR에 포함이 안되어 있어서 어떻게 구현되어 있는지 코드로만 봐야 해서 불편합니다.

2. 탭 동작 UI가 겉보기에 이상합니다. 
![image](https://github.com/not-blond-beard/Savor-22b/assets/56328777/1cf00eb6-36bf-41b6-b64b-571023fbd3ba)
보통 위처럼 생긴 탭은 배경 색과 선택한 하이라이트 색상이 같아야 하는데요.
반대로 되어 있어서 현재 선택된 탭이 무엇인지 엄청 헷갈립니다. 

3. 판매 목록 UI에서 품목명이 길어지면 잘리거나 ... 으로 처리될 것 같은데 
저정도 여유 공간만 있다면.. 품목명에 따라 정상적으로 모두 표출되는 구간이 많이 짧은 것 같습니다.

4. 인벤토리 UI에서도 마찬가지로 텍스트가 정상적으로 표출되는 구간이 짧습니다. 그리고 stateID는 지금 아예 화면상에서만 봐도 잘린 것 같은데요..

5. 판매 목록 UI의 게시자도 마찬가지 입니다. 잘린 것 같습니다. 

첨언하자면 전체적으로 기본적인 부분이라고 생각되는 것들이 많이 미흡한데.. 리뷰를 받기 전에 스스로 체크해주실 수 있는 부분이라고 생각합니다. 지금보다 더 챙겨주시면 좋을 것 같습니다.

2024-05-27 10:43 UTC, upa-r-upa requested changes
수정하신거 확인 했습니다. 고생 하셨어요.
일단 말씀 드린 것 자체는 수정이 대부분 된 것 같은데,
다시 보니 더 눈에 보이는 것들이 있네요.

1. 이제 보니 페이지 제목이 '무역 화면' 이네요. 최소한 무역 상점이나 다른 이름을 보여주어야 하지 않을까요. 기본적인 부분이라고 생각해서 조금 아쉽습니다.
2. 마찬가지로 버튼 배치나, 복잡한 UI 개선은 뒤로 하더라도 '무역으로'  라는 버튼은 말이 좀 이상합니다. 
3. 그리고 내 판매 목록 UI와 일반 판매 목록 UI가 같은건 잘못됐습니다. 말씀 드린것처럼 기능에 대해 최소한으로는 고민해보고 만드시는 게 중요합니다. 일단 적어도 내가 판매할 아이템 목록에 구매 버튼이 뜨는 건 어색할 것 같습니다.
4. 지금 내 판매목록 UI가 API만 붙이면 사용 가능한 화면이라 보이지 않습니다. 정말 필수적으로 필요한 기능이라고 보여지는 게 없습니다. 
기본적으로 1.내가 올린 판매 물품을 확인하고, 2. 등록을 취소하는 기능은 되어야 하지 않을까요.
5. 그리고 인벤토리에서 StateId가 필요한 이유가 있을까요? 같은 등급, 같은 아이템이라면 묶어서 보여주거나 하는 게 더 용이해 보입니다. 
6. 인벤토리는 탭 기능이 나중에 추가 될 예정이 아니라면.. 탭이 아닌데 탭 UI일 필요가 없어 보입니다.

2024-05-27 16:36 UTC, upa-r-upa commented
수정 고생하셨습니다. 잘 수정 하셨습니다.
조금만 더 수정하면 될 것 같습니다.

- '무역 상점' 이라고 페이지 명을 확정하셨으면, 버튼도 '무역 하러 가기'보다는 용어 통일을 해야할 것 같습니다. '무역 상점' 정도로 통일하면 될 것 같습니다.
- 자세히 보니 판매목록/내 판매목록 모두 아이템 등급이 표기가 안되고 있는 것 같습니다. 등급이 있는 음식이나 식재료는 등급이 표시 되어야 합니다.

2024-05-28 06:51 UTC, Atralupus commented
확인되기 전에 resolved는 누르지 말아주세요

2024-05-28 06:55 UTC, upa-r-upa commented
수정 고생하셨습니다. 제가 말씀 드린 내용들은 잘 수정 된 것 같네요. 
하나 그냥 알려드리자면 commit message에 #number 와 같은 식으로 적는 건 issue나 pr 번호로 인식되니까 지양하시는 게 좋습니다.
또 웬만하면 ui problems와 같이 추상적이고 여러 내용이 묶인 커밋도 지양하시는 게 좋습니다. 커밋을 나눠서 내용에 맞추어 메시지를 작성해주시면 좋습니다.

2024-05-28 07:12 UTC, Atralupus requested changes

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/sell_list_button_group.tres
> +[gd_resource type="ButtonGroup" format=3 uid="uid://di66p0jb8cdpk"]
sell_list 파일 이름에 아직 있습니다

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.gd
> +func _on_my_sell_list_button_down():
sell_list

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.gd
> +func _on_whole_sell_list_button_down():
sell_list

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.tscn
> +[ext_resource type="ButtonGroup" uid="uid://di66p0jb8cdpk" path="res://scenes/market/sell_list_button_group.tres" id="2_68j2i"]
sell_list

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.tscn
> +[connection signal="button_down" from="MarginContainer/VBoxContainer/HBoxContainer/WholeSellListButton" to="." method="_on_whole_sell_list_button_down"]
sell_list

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.tscn
> +[connection signal="button_down" from="MarginContainer/VBoxContainer/HBoxContainer/MySellListButton" to="." method="_on_my_sell_list_button_down"]
sell_list

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +extends Control
저희 이미 상점이 있고 여기는 무역상점이라 백엔드에선 TradeStore 라는 용어로 사용 중입니다 헷갈릴 수 있으니 네이밍 전체적으로 변경 부탁드립니다

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +const SellListScn = preload("res://scenes/market/trade_inventory.tscn")
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +		var trade_inventory = SellListScn.instantiate()
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.tscn
> +[node name="SellListMarginContainer" type="MarginContainer" parent="VBoxContainer/MarginContainer/SubMenuHBoxContainer"]
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.tscn
> +[node name="SellList" type="Control"]
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.tscn
> +[node name="WholeSellListButton" type="Button" parent="MarginContainer/VBoxContainer/HBoxContainer"]
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +@onready var trade_inventory_container = $VBoxContainer/MarginContainer/SubMenuHBoxContainer/SellListMarginContainer
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.tscn
> +[node name="MySellListButton" type="Button" parent="MarginContainer/VBoxContainer/HBoxContainer"]
SellList

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_goods.gd
> +var desc_format_string = "%s : %s
들여쓰기는 실제로 엔터를 넣지 마시고 \n으로 쓰시면 됩니다
"%s : %s\n%s %s\n~~~"

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/village/village_view.gd
> +
들여쓰기 통일해주세요 포메터나 린터 생기기 전까진 신경 써주시기 바랍니다

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/my_trade_goods.tscn
> +text = "   가격 수정   "
패딩 이렇게 공백으로주지 마시고 실제 스타일 테마 오버라이드 하셔서 패딩 또는 마진 값 설정해주세요

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/my_item.gd
> +@onready var item_name_label = $Background/MarginContainer/VBoxContainer/NameLabel
필수 수정사항은 아닙니다만 노드들 이름에 굳이 VBox, Margin 이런 기능적인 이름들 다 제거해주시면 좋겠습니다

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/market.gd
> +func props_only_query_action(query_executor): # query with no args
아직 이름이 명확하지 않습니다. 또 따로 함수로 존재할 필요가 없어보입니다.
인자로 받는 query_executor가 특정한 query_executor만 사용 가능해보이고 이벤트 리스너를 등록하는 것이기 때문에 해당 함수에서 진행할 이유 또한 없습니다. 결국 해주는건 `run` 을 실행해주는건데 이걸 따로 해주는 함수가 필요하진 않아보입니다.

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/my_item.gd
> +	item_name_label.text = info[0]["name"]
이부분은 파악해보질 못했는데 0 인덱스로 접근해도 괜찮은건가요? 또 변수명으로 보아 정보를 받아오는 것 같은데 왜 Array인가요?

2024-05-28 07:12 UTC, Atralupus commented on frontend/Savor-22b/scenes/market/trade_inventory.gd
> +func set_list(data: Array):
이부분까지는 크게 상관 없는데 항상 네이밍은 더 명확하게 해주세요
set_list 보단 지금 goods에 데이터를 set 해주시니까 set_goods가 더 맞아보입니다 또 load까지 진행하니 set_goods_and_load가 될텐데 set_goods만 두고 load는 따로 호출해주는게 맞겠습니다

2024-05-29 07:39 UTC, merged