[SVR-18]Feat/create ingredients
not-blond-beard/savor22b pull request #35
Opened 2023-07-31 13:04 UTC by kth1888

같은 원리의 코드 마찬가지로 작성했습니다. UI는 재사용했습니다.

2023-07-31 13:59 UTC, Atralupus requested changes

2023-07-31 13:59 UTC, Atralupus commented on frontend/Savor-22b/Assets/Scripts/CreateIngredient.cs
> +    public string seedSId = "f2076c04-bd3d-4ed3-8475-63fbe84fd124";
pk hex는 지금 테스트 단계이니 하드코딩해도 무방하나 seed id의 경우 guid라서 seed마다, 계속 달라지는 unique key 값 입니다. 따라서 하드코딩 해둔다면 해당 seed가 소진되었을 때 이후 액션을 실행하지 못합니다
간단하게 seed들을 list 뷰로 ui에 보여주고 클릭하면 ingredient로 업그레이드하도록? 작업해도 괜찮을 것 같은데 방식은 상관 없으나 guid를 전달 받을 수 있어야합니다

2023-07-31 13:59 UTC, Atralupus commented on frontend/Savor-22b/Assets/Scripts/CreateIngredient.cs
> +    public string seedSId = "f2076c04-bd3d-4ed3-8475-63fbe84fd124";
(그리고 오타가 있어요!)

2023-08-04 05:10 UTC, upa-r-upa commented
ready for review로 바꾸신 것 같은데 아직 리뷰에 대한 수정 사항이 적용이 안된 것 같아여

2023-08-10 09:15 UTC, kth1888 commented
1. 섭스 무한 유지 및 생성 버튼 삭제 2. 섭스에서 변경사항(시드가 추가 생성) 될 시 리스트가 추가되도록 변경 3. 한 게임에 시드 생성과 리스트 생성을 확인하기 위해 CreateSeed <-> CreateIngredient 간 전환 기능 추가 4. 씬 전환 없이 종자 생성 가능한 버튼 추가

2023-08-10 11:17 UTC, Atralupus approved these changes

2023-08-10 11:30 UTC, merged